[connections.snowpark]
user = "Karel"
password = "Enigma1357."
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "jf86647.eu-central-1"

OPENAI_API_KEY = "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"